core/urls.py
from django.urls import path
from core import views


app_name = 'core'

urlpatterns =[
    path('',views.index, name='main_page'),
    path('cl_list', views.ClientsList.as_view(), name='cl_list'),
    path('client/<int:pk>', views.DetailClient.as_view(), name='detail_cl'),
    path('websites',views.WebsitesList.as_view(), name='ws_list'),
    path('website/<int:pk>',views.DetailWebsite.as_view(), name='detail_ws'),
    path('cl_create', views.CreateClient.as_view(), name='cl_create'),
    path('cl_update/<int:pk>', views.UpdateClient.as_view(), name='cl_update'),
    path('cl_delete/<int:pk>',views.DeleteClient.as_view(), name='cl_delete')
]

hosting/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models
from django.utils import timezone


class DomainNameServer(models.Model):
    address = models.CharField(max_length=40, blank=True) #адрес ДНС сервера


class Client(models.Model):

    login = models.CharField(max_length=30, null=False)
    password = models.CharField(max_length=30, null=False, blank=True)
    dns_server = models.CharField(max_length=30, null=False, blank=True) # доступные ДНС серверы


class Website(models.Model):
    name = models.CharField(max_length=50, null=False, blank=True) # адрес сайта
    address = models.CharField(max_length=40, null=False, blank=True) # IP-адрес сайта
    owner = models.CharField(max_length=40, null=False, blank=True) # связь с владельцем
    expires = models.DateTimeField(default=timezone.now() + timezone.timedelta(days=30)) # дата и время окончания аренды


core/forms.py
from django import forms
from core import models

forbidden_characters = "'!@#$%^&*()\/"


class ClientForm(forms.ModelForm):
    login = forms.CharField(label='логин клиента',required=True)
    password = forms.CharField(label='пароль клиента', required=True)

    class Meta:
        model = models.Client
        fields = '__all__'


class ClientSearch(forms.Form):

    def clean_client_login(self):
        login = list(self.cleaned_data['client_login'])
        if list(filter(lambda x: x in forbidden_characters, login)):
            raise forms.ValidationError(f'Имя не должно содержать символов {forbidden_characters}')
        return login
    client_login = forms.CharField(label='Логин клиента',required=False)


class WebsiteSearch(forms.Form):
    website_name = forms.CharField(label='поиск по имени сайта', required=False)
    website_url = forms.CharField(label='поиск по адресу сайта', required=False)
    website_owner = forms.CharField(label='поиск по владельцу сайта', required=False)

    def clean(self):
        name = list(self.cleaned_data['website_name'])
        url = list(self.cleaned_data['website_url'])
        owner = list(self.cleaned_data['website_owner'])
        if list(filter(lambda x: x in forbidden_characters, name)):
            raise forms.ValidationError(f'Имя сайта не должно содержать символов {forbidden_characters}')

        if list(filter(lambda x: x in forbidden_characters, url)):
            raise forms.ValidationError(f'Адрес не должен содержать символов {forbidden_characters}')

        if list(filter(lambda x: x in forbidden_characters, owner)):
            raise forms.ValidationError(f'Имя влдельца не должно содержать символов {forbidden_characters}')
        return name

core/views.py
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from core import models, forms


class TitleMixin:
    title = None

    def get_title(self):
        return self.title

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.get_title()
        return context


def index(request):
    return render(request=request, template_name='core/index.html')


class ClientsList(ListView, TitleMixin):
    model = models.Client
    template_name = 'core/clients_list.html'
    context_object_name = 'clients'

    def get_queryset(self):
        client_login = self.request.GET.get('client_login')
        qset = models.Client.objects.all()
        if client_login:
            return qset.filter(login__icontains=client_login)
        return qset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.ClientSearch(self.request.GET)
        return context


class DetailClient(DetailView):
    model = models.Client
    template_name = 'core/client.html'
    context_object_name = 'client'


class CreateClient(CreateView):
    model = models.Client
    template_name = 'core/create_client.html'
    form_class = forms.ClientForm
    success_url = reverse_lazy('core:cl_list')


class UpdateClient(UpdateView):
    model = models.Client
    template_name = 'core/client_update.html'
    form_class = forms.ClientForm
    success_url = reverse_lazy('core:cl_list')


class DeleteClient(DeleteView):
    model = models.Client
    template_name = 'core/client_delete.html'
    success_url = reverse_lazy('core:cl_list')


class WebsitesList(ListView, TitleMixin):
    model = models.Website
    template_name = 'core/websites_list.html'
    context_object_name = 'websites'

    def get_queryset(self):
        website_name = self.request.GET.get('website_name')
        website_url = self.request.GET.get('website_url')
        website_owner = self.request.GET.get('website_owner')
        qset = models.Website.objects.all()
        if website_name:
            return qset.filter(Q(name__icontains=website_name) | Q(address__icontains=website_url) | Q(owner=website_owner))
        return qset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = forms.WebsiteSearch(self.request.GET)
        return context


class DetailWebsite(DetailView):
    model = models.Website
    template_name = 'core/website.html'
    context_object_name = 'website'


core/templates/core/based.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <style>
        body {
        padding: 20px;
        }
        #butn {
        margin: 10px;
        }
    </style>
</head>
<body>
    <h1>SpritePlusMilk</h1>

    <a id = "butn" tabindex="0" class="btn btn-lg btn-danger" role="button" data-bs-toggle="popover"
       data-bs-trigger="focus" data-bs-title="(づ ᴗ _ᴗ)づ"
       data-bs-content="Написать тесты для вьюх">Домашнее задание №10</a>



    <nav class="nav">
  <a class="nav-link" href="{% url 'core:cl_list'%}">список пользователей</a>
  <a class="nav-link" href="{% url 'core:ws_list'%}">список вебсайтов</a>
  <a class="nav-link" href="{% url 'core:main_page'%}">домой</a>

</nav>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <script>
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
    </script>

</body>
</html>

core/templates/core/client.html
{% extends 'core/based.html'%}
{% block content%}

    <h1>{{client.login}}</h1>
    <h2>{{client.dns_server}}</h2>
<a href="{% url 'core:cl_list' %}"><button type="button" class="btn btn-outline-primary">Назад</button></a>
<a href="{% url 'core:cl_update' client.id %}"><button type="button" class="btn btn-outline-primary">Обновить</button></a>
<a href="{% url 'core:cl_delete' client.id %}"><button type="button" class="btn btn-outline-primary">Удалить</button></a>

{% endblock %}

core/templates/core/client_delete.html
{% extends 'core/based.html'%}
{% block content%}

<form action = "{% url 'core:cl_delete' client.id%}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-outline-primary">Удалить {{client.login}}? </button>
</form>


{% endblock %}

core/templates/core/client_update.html
{% extends 'core/based.html'%}
{% block content%}

<form action = "{% url 'core:cl_update' client.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit"> Добавить</button>
</form>

{% endblock %}

core/templates/core/clients_list.html
{% extends 'core/based.html'%}
{% block content%}

<form method="get">
  {{form}}
  <button type="submit">Поиск</button>
</form>
<a href="{% url 'core:cl_create' %}"><button type="submit" class="btn btn-outline-primary"> Добавить клиента</button></a>

<h1>Список клиентов:</h1>
<ul>
{% for client in clients %}
    <li><a href="{% url 'core:detail_cl' client.id %}">{{client.login}}</a> <br>
        <a>{{client.dns_server}}</a>

{% endfor %}
</ul>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

{% endblock %}

core/templates/core/create_client.html
{% extends 'core/based.html'%}
{% block content%}

<form action = "{% url 'core:cl_create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit"> Добавить</button>
</form>

{% endblock %}

core/templates/core/index.html
{% extends 'core/based.html'%}

core/templates/core/website.html
{% extends 'core/based.html'%}
{% block content%}


<h1>Данные о сайте {{website.name}}:</h1>
<p>Адрес: {{website.address}}</p>
<p>Логин владельца: {{website.owner.login}}</p>
<p>Аренда заканчивается: {{website.expires}}</p>

<a href="{% url 'core:ws_list' %}"><button type="button" class="btn btn-outline-primary">Назад</button></a>

{% endblock %}

core/templates/core/websites_list.html
{% extends 'core/based.html'%}
{% block content%}

<form method="get">
  {{form}}
  <button type="submit">Поиск</button>
</form>


<h1>Список вебсайтов:</h1>
<ul>
{% for website in websites %}
    <li><a href="{% url 'core:detail_ws' website.id %}">{{website.name}}</a> <br>
        <a>url: {{website.address}}</a> <br>
        <a>Логин владельца: {{website.owner.login}}</a>
    </li>

{% endfor %}
</ul>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>


{% endblock %}